ENT.Base = "base_entity"
ENT.Type = "anim"
ENT.PrintName = "Radio"
ENT.Author = "Abel Witz"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.RenderGroup = RENDERGROUP_OPAQUE
ENT.Category = "Nutscript"
ENT.isMusicRadio = true